#!/usr/bin/env ruby

delimiter = '"org-babel-haskell-eoe"'
prompt = "hello> "

def execute_haskell(body)
  io = IO.popen("runhaskell", "r+")
  io.write(body)
  io.close_write
  result = io.read
  io.close
  return result
end

print prompt
body = ''

while line = gets
  if line =~  /#{delimiter}/
    result = execute_haskell(body)
    result.split(/\n/).each do |str|
      print "#{str}\n"
      print "#{prompt} \n"
    end
    print "#{prompt} \n"
    print "#{delimiter}\n"
    print prompt
    body = ''
  else
    body += line
  end
end
